{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Imports"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tqdm\\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import itertools\n",
    "from vespa.package import ApplicationPackage, Field, Schema, Document, RankProfile, HNSW, RankProfile, Component, Parameter, FieldSet, GlobalPhaseRanking, Function\n",
    "from vespa.deployment import VespaDocker\n",
    "from datasets import load_dataset\n",
    "from vespa.io import VespaResponse, VespaQueryResponse"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Settings"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "DATA_DIR = \"../../\"\n",
    "DATA_FILES = [\"arxiv-metadata-oai-snapshot.json\"]\n",
    "SPLIT_SIZE_LIMIT = 100"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "class ArticLE:\n",
    "\n",
    "    def __init__(self, a: 'ArticLE' = None):\n",
    "        self.startup(a)\n",
    "    \n",
    "    def startup(self, a: 'ArticLE' = None):\n",
    "        if a is not None:\n",
    "            self.package = a.package\n",
    "            self.docker = a.docker\n",
    "            self.app = a.app\n",
    "        else:\n",
    "            self.set_package()\n",
    "            self.set_docker()\n",
    "            self.set_app()\n",
    "    \n",
    "    def set_package(self):\n",
    "        self.package = ApplicationPackage(\n",
    "        name=\"hybridsearch\",\n",
    "        schema=[Schema(\n",
    "            name=\"doc\",\n",
    "            document=Document(\n",
    "                fields=[\n",
    "                    Field(name=\"id\", type=\"string\", indexing=[\"summary\"]),\n",
    "                    Field(name=\"title\", type=\"string\", indexing=[\"index\", \"summary\"], index=\"enable-bm25\"),\n",
    "                    Field(name=\"body\", type=\"string\", indexing=[\"index\", \"summary\"], index=\"enable-bm25\", bolding=True),\n",
    "                    Field(name=\"embedding\", type=\"tensor<float>(x[384])\",\n",
    "                        indexing=[\"input title . \\\" \\\" . input body\", \"embed\", \"index\", \"attribute\"],\n",
    "                        ann=HNSW(distance_metric=\"angular\"),\n",
    "                        is_document_field=False\n",
    "                    )\n",
    "                ]\n",
    "            ),\n",
    "            fieldsets=[\n",
    "                FieldSet(name = \"default\", fields = [\"title\", \"body\"])\n",
    "            ],\n",
    "            rank_profiles=[\n",
    "                RankProfile(\n",
    "                    name=\"bm25\",\n",
    "                    inputs=[(\"query(q)\", \"tensor<float>(x[384])\")],\n",
    "                    functions=[Function(\n",
    "                        name=\"bm25sum\", expression=\"bm25(title) + bm25(body)\"\n",
    "                    )],\n",
    "                    first_phase=\"bm25sum\"\n",
    "                ),\n",
    "                RankProfile(\n",
    "                    name=\"semantic\",\n",
    "                    inputs=[(\"query(q)\", \"tensor<float>(x[384])\")],\n",
    "                    first_phase=\"closeness(field, embedding)\"\n",
    "                ),\n",
    "                RankProfile(\n",
    "                    name=\"fusion\",\n",
    "                    inherits=\"bm25\",\n",
    "                    inputs=[(\"query(q)\", \"tensor<float>(x[384])\")],\n",
    "                    first_phase=\"closeness(field, embedding)\",\n",
    "                    global_phase=GlobalPhaseRanking(\n",
    "                        expression=\"reciprocal_rank_fusion(bm25sum, closeness(field, embedding))\",\n",
    "                        rerank_count=1000\n",
    "                    )\n",
    "                )\n",
    "            ]\n",
    "        )\n",
    "        ],\n",
    "        components=[Component(id=\"e5\", type=\"hugging-face-embedder\",\n",
    "            parameters=[\n",
    "                Parameter(\"transformer-model\", {\"url\": \"https://github.com/vespa-engine/sample-apps/raw/master/simple-semantic-search/model/e5-small-v2-int8.onnx\"}),\n",
    "                Parameter(\"tokenizer-model\", {\"url\": \"https://raw.githubusercontent.com/vespa-engine/sample-apps/master/simple-semantic-search/model/tokenizer.json\"})\n",
    "            ]\n",
    "        )]\n",
    "    )\n",
    "\n",
    "    def set_docker(self):\n",
    "        self.docker = VespaDocker()\n",
    "    \n",
    "    def set_app(self):\n",
    "        self.app = self.docker.deploy(application_package=self.package)\n",
    "    \n",
    "    def callback(self, response):\n",
    "        if not response.is_successful():\n",
    "            print(f\"Error when feeding document {id}: {response.get_json()}\")\n",
    "    \n",
    "    def feed_json(self, data_files, **kwargs):\n",
    "        dataset = load_dataset(\n",
    "            \"json\",\n",
    "            data_dir=DATA_DIR,\n",
    "            data_files=data_files,\n",
    "            split=f\"train[0:{SPLIT_SIZE_LIMIT}]\",\n",
    "        )\n",
    "        vespa_feed = dataset.map(lambda x: {\"id\": x[\"id\"], \"fields\": { \"title\": x[\"title\"], \"body\": x[\"abstract\"], \"id\": x[\"id\"]}})\n",
    "        self.app.feed_iterable(vespa_feed, schema=\"doc\", namespace=\"article\", callback=self.callback)\n",
    "        \n",
    "    def hits_to_df(self, response:VespaQueryResponse) -> pd.DataFrame:\n",
    "        records = []\n",
    "        fields = [\"id\", \"title\", \"body\"]\n",
    "        for hit in response.hits:\n",
    "            record = {}\n",
    "            for field in fields:\n",
    "                record[field] = hit['fields'][field]\n",
    "            record[\"relevance\"] = hit[\"relevance\"]\n",
    "            records.append(record)\n",
    "        return pd.DataFrame(records)\n",
    "    \n",
    "    def query(self, query, n_hits: int = 5):\n",
    "        with self.app.syncio(connections=1) as session:\n",
    "            response:VespaQueryResponse = session.query(\n",
    "                yql=f\"select * from sources * where userQuery() limit {n_hits}\",\n",
    "                query=query,\n",
    "                ranking=\"bm25\",\n",
    "            )\n",
    "        assert(response.is_successful())\n",
    "        return self.hits_to_df(response)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Waiting for configuration server, 0/300 seconds...\n",
      "Waiting for configuration server, 5/300 seconds...\n",
      "Waiting for configuration server, 10/300 seconds...\n",
      "Waiting for configuration server, 15/300 seconds...\n",
      "Using plain http against endpoint http://localhost:8080/ApplicationStatus\n",
      "Waiting for application status, 0/300 seconds...\n",
      "Using plain http against endpoint http://localhost:8080/ApplicationStatus\n",
      "Waiting for application status, 5/300 seconds...\n",
      "Using plain http against endpoint http://localhost:8080/ApplicationStatus\n",
      "Waiting for application status, 10/300 seconds...\n",
      "Using plain http against endpoint http://localhost:8080/ApplicationStatus\n",
      "Waiting for application status, 15/300 seconds...\n",
      "Using plain http against endpoint http://localhost:8080/ApplicationStatus\n",
      "Waiting for application status, 20/300 seconds...\n",
      "Using plain http against endpoint http://localhost:8080/ApplicationStatus\n",
      "Waiting for application status, 25/300 seconds...\n",
      "Using plain http against endpoint http://localhost:8080/ApplicationStatus\n",
      "Waiting for application status, 30/300 seconds...\n",
      "Using plain http against endpoint http://localhost:8080/ApplicationStatus\n",
      "Waiting for application status, 35/300 seconds...\n",
      "Using plain http against endpoint http://localhost:8080/ApplicationStatus\n",
      "Application is up!\n",
      "Finished deployment.\n"
     ]
    }
   ],
   "source": [
    "a = ArticLE()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in user callback for id 0704.0001\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0002\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0003\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0004\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0005\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0006\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0007\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0008\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0009\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0010\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0011\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0012\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0013\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0014\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0015\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0016\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0017\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0018\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0019\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0020\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0021\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0022\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0023\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0024\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0025\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0026\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0027\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0028\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0029\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0030\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0031\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0032\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0033\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0034\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0035\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0036\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0037\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0038\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0039\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0040\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0041\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0042\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0043\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0044\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0045\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0046\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0047\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0048\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0049\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0050\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0051\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0052\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0053\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0054\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0055\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0056\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0057\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0058\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0059\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0060\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0061\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0062\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0063\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0064\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0065\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0066\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0067\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0068\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0069\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0070\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0071\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0072\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0073\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0074\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0075\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0076\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0077\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0078\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0079\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0080\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0081\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0082\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0083\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0084\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0085\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0086\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0087\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0088\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0089\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0090\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0091\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0092\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0093\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0094\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0095\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0096\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0097\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0098\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0099\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n",
      "Exception in user callback for id 0704.0100\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\vespa\\application.py\", line 426, in _handle_result_callback\n",
      "    callback(response,id=id)\n",
      "TypeError: callback() got an unexpected keyword argument 'id'\n"
     ]
    }
   ],
   "source": [
    "a.feed_json(DATA_FILES)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>title</th>\n",
       "      <th>body</th>\n",
       "      <th>relevance</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0704.0773</td>\n",
       "      <td>Collective behavior of stock price movements i...</td>\n",
       "      <td>To investigate the universality of the struc...</td>\n",
       "      <td>33.164795</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>0705.0076</td>\n",
       "      <td>Deterministic Factors of Stock Networks based ...</td>\n",
       "      <td>The &lt;hi&gt;stock&lt;/hi&gt; &lt;hi&gt;market&lt;/hi&gt; has been ...</td>\n",
       "      <td>31.788707</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>0704.0664</td>\n",
       "      <td>Stock market return distributions: from past t...</td>\n",
       "      <td>We show that recent &lt;hi&gt;stock&lt;/hi&gt; &lt;hi&gt;marke...</td>\n",
       "      <td>30.394020</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>0704.2115</td>\n",
       "      <td>Uncovering the Internal Structure of the India...</td>\n",
       "      <td>The cross-correlations between price fluctua...</td>\n",
       "      <td>23.351139</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>0704.3905</td>\n",
       "      <td>Ensemble Learning for Free with Evolutionary A...</td>\n",
       "      <td>Evolutionary &lt;hi&gt;Learning&lt;/hi&gt; proceeds by e...</td>\n",
       "      <td>21.473587</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>0704.3453</td>\n",
       "      <td>An Adaptive Strategy for the Classification of...</td>\n",
       "      <td>One of the major problems in computational b...</td>\n",
       "      <td>21.080254</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>0705.0666</td>\n",
       "      <td>Validating module network learning algorithms ...</td>\n",
       "      <td>In recent years, several authors have used p...</td>\n",
       "      <td>20.383808</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>0705.4023</td>\n",
       "      <td>The limit order book on different time scales</td>\n",
       "      <td>Financial &lt;hi&gt;markets&lt;/hi&gt; can be described ...</td>\n",
       "      <td>19.814361</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>0704.2139</td>\n",
       "      <td>Why only few are so successful ?</td>\n",
       "      <td>In many professons employees are rewarded ac...</td>\n",
       "      <td>18.524608</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>0704.1099</td>\n",
       "      <td>The Epps effect revisited</td>\n",
       "      <td>We analyse the dependence of &lt;hi&gt;stock&lt;/hi&gt; ...</td>\n",
       "      <td>18.062398</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "          id                                              title  \\\n",
       "0  0704.0773  Collective behavior of stock price movements i...   \n",
       "1  0705.0076  Deterministic Factors of Stock Networks based ...   \n",
       "2  0704.0664  Stock market return distributions: from past t...   \n",
       "3  0704.2115  Uncovering the Internal Structure of the India...   \n",
       "4  0704.3905  Ensemble Learning for Free with Evolutionary A...   \n",
       "5  0704.3453  An Adaptive Strategy for the Classification of...   \n",
       "6  0705.0666  Validating module network learning algorithms ...   \n",
       "7  0705.4023      The limit order book on different time scales   \n",
       "8  0704.2139                   Why only few are so successful ?   \n",
       "9  0704.1099                          The Epps effect revisited   \n",
       "\n",
       "                                                body  relevance  \n",
       "0    To investigate the universality of the struc...  33.164795  \n",
       "1    The <hi>stock</hi> <hi>market</hi> has been ...  31.788707  \n",
       "2    We show that recent <hi>stock</hi> <hi>marke...  30.394020  \n",
       "3    The cross-correlations between price fluctua...  23.351139  \n",
       "4    Evolutionary <hi>Learning</hi> proceeds by e...  21.473587  \n",
       "5    One of the major problems in computational b...  21.080254  \n",
       "6    In recent years, several authors have used p...  20.383808  \n",
       "7    Financial <hi>markets</hi> can be described ...  19.814361  \n",
       "8    In many professons employees are rewarded ac...  18.524608  \n",
       "9    We analyse the dependence of <hi>stock</hi> ...  18.062398  "
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = a.query(\"Machine learning and data science and stock market\", n_hits=10)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  To investigate the universality of the structure of interactions in different\n",
      "<hi>markets</hi>, we analyze the cross-correlation matrix C of <hi>stock</hi> price fluctuations\n",
      "in the National <hi>Stock</hi> Exchange (NSE) of India. We find that this emerging\n",
      "<hi>market</hi> exhibits strong correlations in the movement of <hi>stock</hi> prices compared to\n",
      "developed <hi>markets</hi>, such as the New York <hi>Stock</hi> Exchange (NYSE). This is shown to\n",
      "be due to the dominant influence of a common <hi>market</hi> mode on the <hi>stock</hi> prices.\n",
      "By comparison, interactions between related stocks, e.g., those belonging to\n",
      "the same business sector, are much weaker. This lack of distinct sector\n",
      "identity in emerging <hi>markets</hi> is explicitly shown by reconstructing the network\n",
      "of mutually interacting stocks. Spectral analysis of C for NSE reveals that,\n",
      "the few largest eigenvalues deviate from the bulk of the spectrum predicted by\n",
      "random matrix theory, but they are far fewer in number compared to, e.g., NYSE.\n",
      "We show this to be due to the relative weakness of intra-sector interactions\n",
      "between stocks, compared to the <hi>market</hi> mode, by modeling <hi>stock</hi> price dynamics\n",
      "with a two-factor model. Our results suggest that the emergence of an internal\n",
      "structure comprising multiple groups of strongly coupled components is a\n",
      "signature of <hi>market</hi> development.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print(df.loc[0, \"body\"])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
